"""enterprise_database_foundation

Revision ID: e05ac64b85e4
Revises:
Create Date: 2026-07-03 11:53:07.646792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e05ac64b85e4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('bio', sa.String(length=2000), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artists'))
    )
    op.create_index(op.f('ix_artists_id'), 'artists', ['id'], unique=False)
    op.create_index(op.f('ix_artists_is_deleted'), 'artists', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_artists_name'), 'artists', ['name'], unique=False)
    op.create_index(op.f('ix_artists_uuid'), 'artists', ['uuid'], unique=True)
    op.create_table('audit_logs',
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('performed_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_is_deleted'), 'audit_logs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_audit_logs_uuid'), 'audit_logs', ['uuid'], unique=True)
    op.create_table('daily_metrics',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('retention_rate', sa.Float(), nullable=False),
    sa.Column('churn_rate', sa.Float(), nullable=False),
    sa.Column('premium_conversion', sa.Float(), nullable=False),
    sa.Column('total_listening_time_ms', sa.Integer(), nullable=False),
    sa.Column('average_session_ms', sa.Integer(), nullable=False),
    sa.Column('daily_active_users', sa.Integer(), nullable=False),
    sa.Column('segmented_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_metrics'))
    )
    op.create_index(op.f('ix_daily_metrics_date'), 'daily_metrics', ['date'], unique=True)
    op.create_index(op.f('ix_daily_metrics_id'), 'daily_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_daily_metrics_is_deleted'), 'daily_metrics', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_daily_metrics_uuid'), 'daily_metrics', ['uuid'], unique=True)
    op.create_table('dashboard_cache',
    sa.Column('cache_key', sa.String(length=255), nullable=False),
    sa.Column('cache_data', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dashboard_cache'))
    )
    op.create_index(op.f('ix_dashboard_cache_cache_key'), 'dashboard_cache', ['cache_key'], unique=True)
    op.create_index(op.f('ix_dashboard_cache_expires_at'), 'dashboard_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_dashboard_cache_id'), 'dashboard_cache', ['id'], unique=False)
    op.create_index(op.f('ix_dashboard_cache_is_deleted'), 'dashboard_cache', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_dashboard_cache_uuid'), 'dashboard_cache', ['uuid'], unique=True)
    op.create_table('genres',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_genres'))
    )
    op.create_index(op.f('ix_genres_id'), 'genres', ['id'], unique=False)
    op.create_index(op.f('ix_genres_is_deleted'), 'genres', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_genres_name'), 'genres', ['name'], unique=True)
    op.create_index(op.f('ix_genres_uuid'), 'genres', ['uuid'], unique=True)
    op.create_table('model_versions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_versions'))
    )
    op.create_index(op.f('ix_model_versions_id'), 'model_versions', ['id'], unique=False)
    op.create_index(op.f('ix_model_versions_is_deleted'), 'model_versions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_model_versions_name'), 'model_versions', ['name'], unique=False)
    op.create_index(op.f('ix_model_versions_uuid'), 'model_versions', ['uuid'], unique=True)
    op.create_index(op.f('ix_model_versions_version'), 'model_versions', ['version'], unique=False)
    op.create_table('monthly_metrics',
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('retention_rate', sa.Float(), nullable=False),
    sa.Column('churn_rate', sa.Float(), nullable=False),
    sa.Column('premium_conversion', sa.Float(), nullable=False),
    sa.Column('total_listening_time_ms', sa.Integer(), nullable=False),
    sa.Column('average_session_ms', sa.Integer(), nullable=False),
    sa.Column('monthly_active_users', sa.Integer(), nullable=False),
    sa.Column('segmented_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monthly_metrics'))
    )
    op.create_index(op.f('ix_monthly_metrics_id'), 'monthly_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_monthly_metrics_is_deleted'), 'monthly_metrics', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_monthly_metrics_month'), 'monthly_metrics', ['month'], unique=True)
    op.create_index(op.f('ix_monthly_metrics_uuid'), 'monthly_metrics', ['uuid'], unique=True)
    op.create_table('permissions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions'))
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_is_deleted'), 'permissions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_index(op.f('ix_permissions_uuid'), 'permissions', ['uuid'], unique=True)
    op.create_table('retention_cohorts',
    sa.Column('cohort_month', sa.Date(), nullable=False),
    sa.Column('acquisition_source', sa.String(length=100), nullable=False),
    sa.Column('retention_day', sa.Integer(), nullable=True),
    sa.Column('retention_week', sa.Integer(), nullable=True),
    sa.Column('retention_month', sa.Integer(), nullable=True),
    sa.Column('active_users', sa.Integer(), nullable=False),
    sa.Column('retention_rate', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retention_cohorts'))
    )
    op.create_index(op.f('ix_retention_cohorts_cohort_month'), 'retention_cohorts', ['cohort_month'], unique=False)
    op.create_index(op.f('ix_retention_cohorts_id'), 'retention_cohorts', ['id'], unique=False)
    op.create_index(op.f('ix_retention_cohorts_is_deleted'), 'retention_cohorts', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_retention_cohorts_uuid'), 'retention_cohorts', ['uuid'], unique=True)
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_is_deleted'), 'roles', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_index(op.f('ix_roles_uuid'), 'roles', ['uuid'], unique=True)
    op.create_table('subscription_plans',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('billing_cycle', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_plans'))
    )
    op.create_index(op.f('ix_subscription_plans_id'), 'subscription_plans', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_plans_is_deleted'), 'subscription_plans', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_subscription_plans_name'), 'subscription_plans', ['name'], unique=True)
    op.create_index(op.f('ix_subscription_plans_uuid'), 'subscription_plans', ['uuid'], unique=True)
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_settings'))
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    op.create_index(op.f('ix_system_settings_is_deleted'), 'system_settings', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.create_index(op.f('ix_system_settings_uuid'), 'system_settings', ['uuid'], unique=True)
    op.create_table('weekly_metrics',
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('retention_rate', sa.Float(), nullable=False),
    sa.Column('churn_rate', sa.Float(), nullable=False),
    sa.Column('premium_conversion', sa.Float(), nullable=False),
    sa.Column('total_listening_time_ms', sa.Integer(), nullable=False),
    sa.Column('average_session_ms', sa.Integer(), nullable=False),
    sa.Column('weekly_active_users', sa.Integer(), nullable=False),
    sa.Column('segmented_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weekly_metrics'))
    )
    op.create_index(op.f('ix_weekly_metrics_end_date'), 'weekly_metrics', ['end_date'], unique=False)
    op.create_index(op.f('ix_weekly_metrics_id'), 'weekly_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_weekly_metrics_is_deleted'), 'weekly_metrics', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_weekly_metrics_start_date'), 'weekly_metrics', ['start_date'], unique=True)
    op.create_index(op.f('ix_weekly_metrics_uuid'), 'weekly_metrics', ['uuid'], unique=True)
    op.create_table('albums',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('album_type', sa.String(length=50), nullable=True),
    sa.Column('total_tracks', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name=op.f('fk_albums_artist_id_artists')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_albums'))
    )
    op.create_index(op.f('ix_albums_artist_id'), 'albums', ['artist_id'], unique=False)
    op.create_index(op.f('ix_albums_id'), 'albums', ['id'], unique=False)
    op.create_index(op.f('ix_albums_is_deleted'), 'albums', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_albums_release_date'), 'albums', ['release_date'], unique=False)
    op.create_index(op.f('ix_albums_title'), 'albums', ['title'], unique=False)
    op.create_index(op.f('ix_albums_uuid'), 'albums', ['uuid'], unique=True)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles')),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    op.create_table('activity_logs',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_activity_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_logs'))
    )
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    op.create_index(op.f('ix_activity_logs_is_deleted'), 'activity_logs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_uuid'), 'activity_logs', ['uuid'], unique=True)
    op.create_table('devices',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_type', sa.String(length=100), nullable=False),
    sa.Column('operating_system', sa.String(length=100), nullable=True),
    sa.Column('os_version', sa.String(length=50), nullable=True),
    sa.Column('application_version', sa.String(length=50), nullable=True),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_devices_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices'))
    )
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_index(op.f('ix_devices_is_deleted'), 'devices', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.create_index(op.f('ix_devices_uuid'), 'devices', ['uuid'], unique=True)
    op.create_table('favorite_artists',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name=op.f('fk_favorite_artists_artist_id_artists')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_favorite_artists_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'artist_id', name=op.f('pk_favorite_artists'))
    )
    op.create_table('listening_sessions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_listening_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listening_sessions'))
    )
    op.create_index(op.f('ix_listening_sessions_id'), 'listening_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_listening_sessions_is_deleted'), 'listening_sessions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_listening_sessions_start_time'), 'listening_sessions', ['start_time'], unique=False)
    op.create_index(op.f('ix_listening_sessions_user_id'), 'listening_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_listening_sessions_uuid'), 'listening_sessions', ['uuid'], unique=True)
    op.create_table('notifications',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(length=2000), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_deleted'), 'notifications', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_uuid'), 'notifications', ['uuid'], unique=True)
    op.create_table('playlists',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('visibility', sa.String(length=50), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('follower_count', sa.Integer(), nullable=False),
    sa.Column('total_tracks', sa.Integer(), nullable=False),
    sa.Column('total_duration_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_playlists_created_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_playlists'))
    )
    op.create_index(op.f('ix_playlists_created_by_id'), 'playlists', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_playlists_id'), 'playlists', ['id'], unique=False)
    op.create_index(op.f('ix_playlists_is_deleted'), 'playlists', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_playlists_name'), 'playlists', ['name'], unique=False)
    op.create_index(op.f('ix_playlists_uuid'), 'playlists', ['uuid'], unique=True)
    op.create_table('predictions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('prediction_score', sa.Float(), nullable=False),
    sa.Column('retention_probability', sa.Float(), nullable=False),
    sa.Column('churn_probability', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('prediction_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('explainability_reference', sa.String(length=255), nullable=True),
    sa.Column('recommended_action', sa.String(length=255), nullable=True),
    sa.Column('prediction_status', sa.String(length=50), nullable=False),
    sa.Column('inference_duration_ms', sa.Integer(), nullable=True),
    sa.Column('model_latency_ms', sa.Integer(), nullable=True),
    sa.Column('prediction_source', sa.String(length=100), nullable=True),
    sa.Column('execution_environment', sa.String(length=100), nullable=True),
    sa.Column('prediction_trigger', sa.String(length=100), nullable=True),
    sa.Column('pipeline_version', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], name=op.f('fk_predictions_model_version_id_model_versions')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_predictions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_predictions'))
    )
    op.create_index('idx_user_prediction_date', 'predictions', ['user_id', 'prediction_timestamp'], unique=False)
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    op.create_index(op.f('ix_predictions_is_deleted'), 'predictions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_predictions_prediction_timestamp'), 'predictions', ['prediction_timestamp'], unique=False)
    op.create_index(op.f('ix_predictions_risk_level'), 'predictions', ['risk_level'], unique=False)
    op.create_index(op.f('ix_predictions_uuid'), 'predictions', ['uuid'], unique=True)
    op.create_table('search_history',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_search_history_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_history'))
    )
    op.create_index(op.f('ix_search_history_id'), 'search_history', ['id'], unique=False)
    op.create_index(op.f('ix_search_history_is_deleted'), 'search_history', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_search_history_timestamp'), 'search_history', ['timestamp'], unique=False)
    op.create_index(op.f('ix_search_history_user_id'), 'search_history', ['user_id'], unique=False)
    op.create_index(op.f('ix_search_history_uuid'), 'search_history', ['uuid'], unique=True)
    op.create_table('songs',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('track_number', sa.Integer(), nullable=True),
    sa.Column('is_explicit', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], name=op.f('fk_songs_album_id_albums')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_songs'))
    )
    op.create_index(op.f('ix_songs_album_id'), 'songs', ['album_id'], unique=False)
    op.create_index(op.f('ix_songs_id'), 'songs', ['id'], unique=False)
    op.create_index(op.f('ix_songs_is_deleted'), 'songs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_songs_release_date'), 'songs', ['release_date'], unique=False)
    op.create_index(op.f('ix_songs_title'), 'songs', ['title'], unique=False)
    op.create_index(op.f('ix_songs_uuid'), 'songs', ['uuid'], unique=True)
    op.create_table('subscriptions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('renewal_date', sa.Date(), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('trial_start', sa.Date(), nullable=True),
    sa.Column('trial_end', sa.Date(), nullable=True),
    sa.Column('cancellation_channel', sa.String(length=100), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=255), nullable=True),
    sa.Column('renewal_attempts', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], name=op.f('fk_subscriptions_plan_id_subscription_plans')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_subscriptions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions'))
    )
    op.create_index(op.f('ix_subscriptions_end_date'), 'subscriptions', ['end_date'], unique=False)
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_is_deleted'), 'subscriptions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_renewal_date'), 'subscriptions', ['renewal_date'], unique=False)
    op.create_index(op.f('ix_subscriptions_status'), 'subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_uuid'), 'subscriptions', ['uuid'], unique=True)
    op.create_table('user_preferences',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preferred_genres', sa.JSON(), nullable=True),
    sa.Column('preferred_artists', sa.JSON(), nullable=True),
    sa.Column('preferred_languages', sa.JSON(), nullable=True),
    sa.Column('favorite_mood', sa.String(length=50), nullable=True),
    sa.Column('favorite_era', sa.String(length=50), nullable=True),
    sa.Column('preferred_audio_quality', sa.String(length=50), nullable=True),
    sa.Column('crossfade_enabled', sa.Boolean(), nullable=False),
    sa.Column('autoplay_enabled', sa.Boolean(), nullable=False),
    sa.Column('explicit_content_allowed', sa.Boolean(), nullable=False),
    sa.Column('offline_downloads_enabled', sa.Boolean(), nullable=False),
    sa.Column('theme_preference', sa.String(length=20), nullable=False),
    sa.Column('notification_preferences', sa.JSON(), nullable=True),
    sa.Column('recommendation_preference_weight', sa.Float(), nullable=False),
    sa.Column('recommendation_diversity_preference', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_preferences_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_preferences'))
    )
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_user_preferences_is_deleted'), 'user_preferences', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    op.create_index(op.f('ix_user_preferences_uuid'), 'user_preferences', ['uuid'], unique=True)
    op.create_table('user_sessions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions'))
    )
    op.create_index(op.f('ix_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_is_deleted'), 'user_sessions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_sessions_token'), 'user_sessions', ['token'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_sessions_uuid'), 'user_sessions', ['uuid'], unique=True)
    op.create_table('favorite_songs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], name=op.f('fk_favorite_songs_song_id_songs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_favorite_songs_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'song_id', name=op.f('pk_favorite_songs'))
    )
    op.create_table('feature_snapshots',
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], name=op.f('fk_feature_snapshots_prediction_id_predictions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feature_snapshots')),
    sa.UniqueConstraint('prediction_id', name=op.f('uq_feature_snapshots_prediction_id'))
    )
    op.create_index(op.f('ix_feature_snapshots_id'), 'feature_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_feature_snapshots_is_deleted'), 'feature_snapshots', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_feature_snapshots_uuid'), 'feature_snapshots', ['uuid'], unique=True)
    op.create_table('listening_history',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('play_duration_ms', sa.Integer(), nullable=False),
    sa.Column('completion_percentage', sa.Float(), nullable=False),
    sa.Column('skipped', sa.Boolean(), nullable=False),
    sa.Column('skip_count', sa.Integer(), nullable=False),
    sa.Column('repeated', sa.Boolean(), nullable=False),
    sa.Column('shuffle_enabled', sa.Boolean(), nullable=False),
    sa.Column('repeat_mode', sa.String(length=50), nullable=False),
    sa.Column('playback_source', sa.String(length=100), nullable=False),
    sa.Column('recommendation_source', sa.String(length=100), nullable=True),
    sa.Column('network_type', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('application_version', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_listening_history_device_id_devices')),
    sa.ForeignKeyConstraint(['session_id'], ['listening_sessions.id'], name=op.f('fk_listening_history_session_id_listening_sessions')),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], name=op.f('fk_listening_history_song_id_songs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_listening_history_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listening_history'))
    )
    op.create_index('idx_user_listening_date', 'listening_history', ['user_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_listening_history_id'), 'listening_history', ['id'], unique=False)
    op.create_index(op.f('ix_listening_history_is_deleted'), 'listening_history', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_listening_history_session_id'), 'listening_history', ['session_id'], unique=False)
    op.create_index(op.f('ix_listening_history_song_id'), 'listening_history', ['song_id'], unique=False)
    op.create_index(op.f('ix_listening_history_uuid'), 'listening_history', ['uuid'], unique=True)
    op.create_table('payment_history',
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name=op.f('fk_payment_history_subscription_id_subscriptions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_history'))
    )
    op.create_index(op.f('ix_payment_history_id'), 'payment_history', ['id'], unique=False)
    op.create_index(op.f('ix_payment_history_is_deleted'), 'payment_history', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_payment_history_payment_date'), 'payment_history', ['payment_date'], unique=False)
    op.create_index(op.f('ix_payment_history_subscription_id'), 'payment_history', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_payment_history_transaction_id'), 'payment_history', ['transaction_id'], unique=True)
    op.create_index(op.f('ix_payment_history_uuid'), 'payment_history', ['uuid'], unique=True)
    op.create_table('playlist_tracks',
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('added_by_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], name=op.f('fk_playlist_tracks_added_by_id_users')),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], name=op.f('fk_playlist_tracks_playlist_id_playlists')),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], name=op.f('fk_playlist_tracks_song_id_songs')),
    sa.PrimaryKeyConstraint('playlist_id', 'song_id', name=op.f('pk_playlist_tracks'))
    )
    op.create_table('prediction_explanations',
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('feature_name', sa.String(length=100), nullable=False),
    sa.Column('feature_importance', sa.Float(), nullable=False),
    sa.Column('impact_direction', sa.String(length=50), nullable=False),
    sa.Column('importance_rank', sa.Integer(), nullable=False),
    sa.Column('contribution_score', sa.Float(), nullable=False),
    sa.Column('normalized_score', sa.Float(), nullable=False),
    sa.Column('generated_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('visualization_color', sa.String(length=50), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], name=op.f('fk_prediction_explanations_prediction_id_predictions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prediction_explanations'))
    )
    op.create_index(op.f('ix_prediction_explanations_id'), 'prediction_explanations', ['id'], unique=False)
    op.create_index(op.f('ix_prediction_explanations_is_deleted'), 'prediction_explanations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_prediction_explanations_prediction_id'), 'prediction_explanations', ['prediction_id'], unique=False)
    op.create_index(op.f('ix_prediction_explanations_uuid'), 'prediction_explanations', ['uuid'], unique=True)
    op.create_table('prediction_history',
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('snapshot_data', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], name=op.f('fk_prediction_history_prediction_id_predictions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prediction_history'))
    )
    op.create_index(op.f('ix_prediction_history_id'), 'prediction_history', ['id'], unique=False)
    op.create_index(op.f('ix_prediction_history_is_deleted'), 'prediction_history', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_prediction_history_prediction_id'), 'prediction_history', ['prediction_id'], unique=False)
    op.create_index(op.f('ix_prediction_history_uuid'), 'prediction_history', ['uuid'], unique=True)
    op.create_table('recommendations',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_score', sa.Float(), nullable=False),
    sa.Column('algorithm_name', sa.String(length=100), nullable=False),
    sa.Column('algorithm_version', sa.String(length=50), nullable=True),
    sa.Column('generated_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('recommendation_rank', sa.Integer(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('rejected', sa.Boolean(), nullable=False),
    sa.Column('clicked', sa.Boolean(), nullable=False),
    sa.Column('skipped', sa.Boolean(), nullable=False),
    sa.Column('played', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], name=op.f('fk_recommendations_song_id_songs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recommendations_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations'))
    )
    op.create_index(op.f('ix_recommendations_generated_time'), 'recommendations', ['generated_time'], unique=False)
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_recommendations_is_deleted'), 'recommendations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_recommendations_user_id'), 'recommendations', ['user_id'], unique=False)
    op.create_index(op.f('ix_recommendations_uuid'), 'recommendations', ['uuid'], unique=True)
    op.create_table('song_artists',
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('artist_role', sa.String(length=100), nullable=False),
    sa.Column('contribution_percentage', sa.Float(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('verified_collaboration', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name=op.f('fk_song_artists_artist_id_artists')),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], name=op.f('fk_song_artists_song_id_songs')),
    sa.PrimaryKeyConstraint('song_id', 'artist_id', name=op.f('pk_song_artists'))
    )
    op.create_table('song_genres',
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('fk_song_genres_genre_id_genres')),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], name=op.f('fk_song_genres_song_id_songs')),
    sa.PrimaryKeyConstraint('song_id', 'genre_id', name=op.f('pk_song_genres'))
    )
    op.create_table('recommendation_history',
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('historical_state', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], name=op.f('fk_recommendation_history_recommendation_id_recommendations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_history'))
    )
    op.create_index(op.f('ix_recommendation_history_id'), 'recommendation_history', ['id'], unique=False)
    op.create_index(op.f('ix_recommendation_history_is_deleted'), 'recommendation_history', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_recommendation_history_recommendation_id'), 'recommendation_history', ['recommendation_id'], unique=False)
    op.create_index(op.f('ix_recommendation_history_uuid'), 'recommendation_history', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_history_uuid'), table_name='recommendation_history')
    op.drop_index(op.f('ix_recommendation_history_recommendation_id'), table_name='recommendation_history')
    op.drop_index(op.f('ix_recommendation_history_is_deleted'), table_name='recommendation_history')
    op.drop_index(op.f('ix_recommendation_history_id'), table_name='recommendation_history')
    op.drop_table('recommendation_history')
    op.drop_table('song_genres')
    op.drop_table('song_artists')
    op.drop_index(op.f('ix_recommendations_uuid'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_user_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_is_deleted'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_generated_time'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_prediction_history_uuid'), table_name='prediction_history')
    op.drop_index(op.f('ix_prediction_history_prediction_id'), table_name='prediction_history')
    op.drop_index(op.f('ix_prediction_history_is_deleted'), table_name='prediction_history')
    op.drop_index(op.f('ix_prediction_history_id'), table_name='prediction_history')
    op.drop_table('prediction_history')
    op.drop_index(op.f('ix_prediction_explanations_uuid'), table_name='prediction_explanations')
    op.drop_index(op.f('ix_prediction_explanations_prediction_id'), table_name='prediction_explanations')
    op.drop_index(op.f('ix_prediction_explanations_is_deleted'), table_name='prediction_explanations')
    op.drop_index(op.f('ix_prediction_explanations_id'), table_name='prediction_explanations')
    op.drop_table('prediction_explanations')
    op.drop_table('playlist_tracks')
    op.drop_index(op.f('ix_payment_history_uuid'), table_name='payment_history')
    op.drop_index(op.f('ix_payment_history_transaction_id'), table_name='payment_history')
    op.drop_index(op.f('ix_payment_history_subscription_id'), table_name='payment_history')
    op.drop_index(op.f('ix_payment_history_payment_date'), table_name='payment_history')
    op.drop_index(op.f('ix_payment_history_is_deleted'), table_name='payment_history')
    op.drop_index(op.f('ix_payment_history_id'), table_name='payment_history')
    op.drop_table('payment_history')
    op.drop_index(op.f('ix_listening_history_uuid'), table_name='listening_history')
    op.drop_index(op.f('ix_listening_history_song_id'), table_name='listening_history')
    op.drop_index(op.f('ix_listening_history_session_id'), table_name='listening_history')
    op.drop_index(op.f('ix_listening_history_is_deleted'), table_name='listening_history')
    op.drop_index(op.f('ix_listening_history_id'), table_name='listening_history')
    op.drop_index('idx_user_listening_date', table_name='listening_history')
    op.drop_table('listening_history')
    op.drop_index(op.f('ix_feature_snapshots_uuid'), table_name='feature_snapshots')
    op.drop_index(op.f('ix_feature_snapshots_is_deleted'), table_name='feature_snapshots')
    op.drop_index(op.f('ix_feature_snapshots_id'), table_name='feature_snapshots')
    op.drop_table('feature_snapshots')
    op.drop_table('favorite_songs')
    op.drop_index(op.f('ix_user_sessions_uuid'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_token'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_is_deleted'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_expires_at'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_user_preferences_uuid'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_is_deleted'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_subscriptions_uuid'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_status'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_renewal_date'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_plan_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_is_deleted'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_end_date'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_songs_uuid'), table_name='songs')
    op.drop_index(op.f('ix_songs_title'), table_name='songs')
    op.drop_index(op.f('ix_songs_release_date'), table_name='songs')
    op.drop_index(op.f('ix_songs_is_deleted'), table_name='songs')
    op.drop_index(op.f('ix_songs_id'), table_name='songs')
    op.drop_index(op.f('ix_songs_album_id'), table_name='songs')
    op.drop_table('songs')
    op.drop_index(op.f('ix_search_history_uuid'), table_name='search_history')
    op.drop_index(op.f('ix_search_history_user_id'), table_name='search_history')
    op.drop_index(op.f('ix_search_history_timestamp'), table_name='search_history')
    op.drop_index(op.f('ix_search_history_is_deleted'), table_name='search_history')
    op.drop_index(op.f('ix_search_history_id'), table_name='search_history')
    op.drop_table('search_history')
    op.drop_index(op.f('ix_predictions_uuid'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_risk_level'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_prediction_timestamp'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_is_deleted'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_index('idx_user_prediction_date', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_playlists_uuid'), table_name='playlists')
    op.drop_index(op.f('ix_playlists_name'), table_name='playlists')
    op.drop_index(op.f('ix_playlists_is_deleted'), table_name='playlists')
    op.drop_index(op.f('ix_playlists_id'), table_name='playlists')
    op.drop_index(op.f('ix_playlists_created_by_id'), table_name='playlists')
    op.drop_table('playlists')
    op.drop_index(op.f('ix_notifications_uuid'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_deleted'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_listening_sessions_uuid'), table_name='listening_sessions')
    op.drop_index(op.f('ix_listening_sessions_user_id'), table_name='listening_sessions')
    op.drop_index(op.f('ix_listening_sessions_start_time'), table_name='listening_sessions')
    op.drop_index(op.f('ix_listening_sessions_is_deleted'), table_name='listening_sessions')
    op.drop_index(op.f('ix_listening_sessions_id'), table_name='listening_sessions')
    op.drop_table('listening_sessions')
    op.drop_table('favorite_artists')
    op.drop_index(op.f('ix_devices_uuid'), table_name='devices')
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_is_deleted'), table_name='devices')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_activity_logs_uuid'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_is_deleted'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_albums_uuid'), table_name='albums')
    op.drop_index(op.f('ix_albums_title'), table_name='albums')
    op.drop_index(op.f('ix_albums_release_date'), table_name='albums')
    op.drop_index(op.f('ix_albums_is_deleted'), table_name='albums')
    op.drop_index(op.f('ix_albums_id'), table_name='albums')
    op.drop_index(op.f('ix_albums_artist_id'), table_name='albums')
    op.drop_table('albums')
    op.drop_index(op.f('ix_weekly_metrics_uuid'), table_name='weekly_metrics')
    op.drop_index(op.f('ix_weekly_metrics_start_date'), table_name='weekly_metrics')
    op.drop_index(op.f('ix_weekly_metrics_is_deleted'), table_name='weekly_metrics')
    op.drop_index(op.f('ix_weekly_metrics_id'), table_name='weekly_metrics')
    op.drop_index(op.f('ix_weekly_metrics_end_date'), table_name='weekly_metrics')
    op.drop_table('weekly_metrics')
    op.drop_index(op.f('ix_system_settings_uuid'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_is_deleted'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_subscription_plans_uuid'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_name'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_is_deleted'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_id'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_roles_uuid'), table_name='roles')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_is_deleted'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_retention_cohorts_uuid'), table_name='retention_cohorts')
    op.drop_index(op.f('ix_retention_cohorts_is_deleted'), table_name='retention_cohorts')
    op.drop_index(op.f('ix_retention_cohorts_id'), table_name='retention_cohorts')
    op.drop_index(op.f('ix_retention_cohorts_cohort_month'), table_name='retention_cohorts')
    op.drop_table('retention_cohorts')
    op.drop_index(op.f('ix_permissions_uuid'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_is_deleted'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_monthly_metrics_uuid'), table_name='monthly_metrics')
    op.drop_index(op.f('ix_monthly_metrics_month'), table_name='monthly_metrics')
    op.drop_index(op.f('ix_monthly_metrics_is_deleted'), table_name='monthly_metrics')
    op.drop_index(op.f('ix_monthly_metrics_id'), table_name='monthly_metrics')
    op.drop_table('monthly_metrics')
    op.drop_index(op.f('ix_model_versions_version'), table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_uuid'), table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_name'), table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_is_deleted'), table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_id'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_genres_uuid'), table_name='genres')
    op.drop_index(op.f('ix_genres_name'), table_name='genres')
    op.drop_index(op.f('ix_genres_is_deleted'), table_name='genres')
    op.drop_index(op.f('ix_genres_id'), table_name='genres')
    op.drop_table('genres')
    op.drop_index(op.f('ix_dashboard_cache_uuid'), table_name='dashboard_cache')
    op.drop_index(op.f('ix_dashboard_cache_is_deleted'), table_name='dashboard_cache')
    op.drop_index(op.f('ix_dashboard_cache_id'), table_name='dashboard_cache')
    op.drop_index(op.f('ix_dashboard_cache_expires_at'), table_name='dashboard_cache')
    op.drop_index(op.f('ix_dashboard_cache_cache_key'), table_name='dashboard_cache')
    op.drop_table('dashboard_cache')
    op.drop_index(op.f('ix_daily_metrics_uuid'), table_name='daily_metrics')
    op.drop_index(op.f('ix_daily_metrics_is_deleted'), table_name='daily_metrics')
    op.drop_index(op.f('ix_daily_metrics_id'), table_name='daily_metrics')
    op.drop_index(op.f('ix_daily_metrics_date'), table_name='daily_metrics')
    op.drop_table('daily_metrics')
    op.drop_index(op.f('ix_audit_logs_uuid'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_is_deleted'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_artists_uuid'), table_name='artists')
    op.drop_index(op.f('ix_artists_name'), table_name='artists')
    op.drop_index(op.f('ix_artists_is_deleted'), table_name='artists')
    op.drop_index(op.f('ix_artists_id'), table_name='artists')
    op.drop_table('artists')
    # ### end Alembic commands ###
